export const GET_CHATS_REQUEST = 'GET_CHATS_REQUEST';
export const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS';
export const GET_CHATS_FAIL = 'GET_CHATS_FAIL';

export const GET_CHAT_DETAILS_REQUEST = 'GET_CHAT_DETAILS_REQUEST';
export const GET_CHAT_DETAILS_SUCCESS = 'GET_CHAT_DETAILS_SUCCESS';
export const GET_CHAT_DETAILS_FAIL = 'GET_CHAT_DETAILS_FAIL';

export const CREATE_OR_GET_CHAT_REQUEST = 'CREATE_OR_GET_CHAT_REQUEST';
export const CREATE_OR_GET_CHAT_SUCCESS = 'CREATE_OR_GET_CHAT_SUCCESS';
export const CREATE_OR_GET_CHAT_FAIL = 'CREATE_OR_GET_CHAT_FAIL';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';

export const GET_ALL_USERS_IN_CHATS_REQUEST = 'GET_ALL_USERS_IN_CHATS_REQUEST';
export const GET_ALL_USERS_IN_CHATS_SUCCESS = 'GET_ALL_USERS_IN_CHATS_SUCCESS';
export const GET_ALL_USERS_IN_CHATS_FAIL = 'GET_ALL_USERS_IN_CHATS_FAIL';

export const ADD_MESSAGE_ICON_REQUEST = 'ADD_MESSAGE_ICON_REQUEST';
export const ADD_MESSAGE_ICON_SUCCESS = 'ADD_MESSAGE_ICON_SUCCESS';
export const ADD_MESSAGE_ICON_FAIL = 'ADD_MESSAGE_ICON_FAIL';

export const UPDATE_MESSAGE_ICON_REQUEST = 'UPDATE_MESSAGE_ICON_REQUEST';
export const UPDATE_MESSAGE_ICON_SUCCESS = 'UPDATE_MESSAGE_ICON_SUCCESS';
export const UPDATE_MESSAGE_ICON_FAIL = 'UPDATE_MESSAGE_ICON_FAIL';

export const REMOVE_MESSAGE_ICON_REQUEST = 'REMOVE_MESSAGE_ICON_REQUEST';
export const REMOVE_MESSAGE_ICON_SUCCESS = 'REMOVE_MESSAGE_ICON_SUCCESS';
export const REMOVE_MESSAGE_ICON_FAIL = 'REMOVE_MESSAGE_ICON_FAIL';
export const SEARCH_USERS_REQUEST = 'SEARCH_USERS_REQUEST';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAIL = 'SEARCH_USERS_FAIL';
