// src/constants/couponConstants.js
export const GET_ALL_COUPONS_REQUEST = 'GET_ALL_COUPONS_REQUEST';
export const GET_ALL_COUPONS_SUCCESS = 'GET_ALL_COUPONS_SUCCESS';
export const GET_ALL_COUPONS_FAIL = 'GET_ALL_COUPONS_FAIL';

export const DELETE_COUPON_REQUEST = 'DELETE_COUPON_REQUEST';
export const DELETE_COUPON_SUCCESS = 'DELETE_COUPON_SUCCESS';
export const DELETE_COUPON_FAIL = 'DELETE_COUPON_FAIL';
export const DELETE_COUPON_RESET = 'DELETE_COUPON_RESET';

export const UPDATE_COUPON_REQUEST = 'UPDATE_COUPON_REQUEST';
export const UPDATE_COUPON_SUCCESS = 'UPDATE_COUPON_SUCCESS';
export const UPDATE_COUPON_FAIL = 'UPDATE_COUPON_FAIL';
export const UPDATE_COUPON_RESET = 'UPDATE_COUPON_RESET';

export const CREATE_COUPON_REQUEST = 'CREATE_COUPON_REQUEST';
export const CREATE_COUPON_SUCCESS = 'CREATE_COUPON_SUCCESS';
export const CREATE_COUPON_FAIL = 'CREATE_COUPON_FAIL';
export const CREATE_COUPON_RESET = 'CREATE_COUPON_RESET';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const TOGGLE_STATUS_REQUEST = 'TOGGLE_STATUS_REQUEST';
export const TOGGLE_STATUS_SUCCESS = 'TOGGLE_STATUS_SUCCESS';
export const TOGGLE_STATUS_FAIL = 'TOGGLE_STATUS_FAIL';
export const TOGGLE_STATUS_RESET = 'TOGGLE_STATUS_RESET';

export const GET_ACTIVE_COUPONS_REQUEST = 'GET_ACTIVE_COUPONS_REQUEST';
export const GET_ACTIVE_COUPONS_SUCCESS = 'GET_ACTIVE_COUPONS_SUCCESS';
export const GET_ACTIVE_COUPONS_FAIL = 'GET_ACTIVE_COUPONS_FAIL';

