export const GET_SHOP_SUCCESS = "GET_SHOP_SUCCESS";
export const GET_SHOP_FAIL = "GET_SHOP_FAIL";

export const UPDATE_SHOP_SUCCESS = "UPDATE_SHOP_SUCCESS";
export const UPDATE_SHOP_FAIL = "UPDATE_SHOP_FAIL";
export const UPDATE_SHOP_RESET = "UPDATE_SHOP_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
