export const SHOP_STATS_REQUEST = 'SHOP_STATS_REQUEST';
export const SHOP_STATS_SUCCESS = 'SHOP_STATS_SUCCESS';
export const SHOP_STATS_FAIL = 'SHOP_STATS_FAIL';

export const REVENUE_ADMIN_REQUEST = 'REVENUE_ADMIN_REQUEST';
export const REVENUE_ADMIN_SUCCESS = 'REVENUE_ADMIN_SUCCESS';
export const REVENUE_ADMIN_FAIL = 'REVENUE_ADMIN_FAIL';
